### ISSUE TITLE
Can't install on ubuntu

### ISSUE THREAD

**Issue by jrm346** [microsoft/artifacts-keyring#14] opened 2020-01-21 16:31 UTC
I'm trying to install this package on ubuntu in a docker container and get the following error.

``` 
pip install artifacts-keyring
Collecting artifacts-keyring
  Downloading artifacts_keyring-0.2.9-py2.py3-none-any.whl (4.8 MB)
     |████████████████████████████████| 4.8 MB 1.3 MB/s 
Collecting keyring>=16.0
  Downloading keyring-21.1.0-py2.py3-none-any.whl (31 kB)
ERROR: Could not find a version that satisfies the requirement dotnetcore2; sys_platform != "win32" and python_version >= "3.0" (from artifacts-keyring) (from versions: none)
ERROR: No matching distribution found for dotnetcore2; sys_platform != "win32" and python_version >= "3.0" (from artifacts-keyring)
```

it seems that the package requires dot net. and there are no available versions. any help on how i can fix this would be appreciated as we need to download a python package from a devops feed. This was working  before Christmas but one of the more recent commits has broken it for me.

**Comment by jrm346** [comment] 2020-01-21 16:47
seems to have been introduced by commit 43f315ecac15b098b920a0d934b71e42e641ab6a and the change to install_requires in setup.cfg

**Comment by sw23** [comment] 2020-01-21 17:29
Ran into this as well this morning (worked last week) - it appears the latest version of pip handles the requirement differently.  I was able to work around the issue for now by controlling the version of pip being used:
```
python -m pip install --upgrade pip==19.3.1
```

**Comment by salvmd** [comment] 2020-01-21 21:05
Thanks @jrm346 for bringing this to our attention and @sw23 for the workaround. I confirmed that the package can be installed by downgrading to pip 19.3.1. After successfully installing artifacts-keyring, it's OK to upgrade back to pip 20.0.1.

We'll be working on a fix for this.

**Comment by salvmd** [comment] 2020-01-22 02:48
Update: The problem is not related to the requirement we put in place to skip the dotnetcore2 dependency in Windows or when using Python 2. The issue is in the latest version of pip and it's related to this: https://github.com/pypa/pip/issues/7626. Because of that issue, it's not possible to install dotnetcore2 (https://pypi.org/project/dotnetcore2/2.1.11/) using pip 20.0.1 (regardless of platform). Ufortunately, until that is fixed, the only workaround is to downgrade to pip 19.3.1.

**Comment by jrm346** [comment] 2020-01-22 08:58
Thanks for the quick response @sw23 and @salvmd. Might be worth changing the pip requirement on the readme until the pip issue is resolved?

**Comment by eibrunorodrigues** [comment] 2020-01-27 13:33
The problem with pip was fixed, but I still got this error. 


ERROR: Could not find a version that satisfies the requirement dotnetcore2; sys_platform != "win32" and python_version >= "3.0" (from artifacts-keyring) (from versions: none)
ERROR: No matching distribution found for dotnetcore2; sys_platform != "win32" and python_version >= "3.0" (from artifacts-keyring)

**Comment by salvmd** [comment] 2020-02-06 23:44
@eibrunorodrigues, sorry I missed your post. What platform and Python version are you using?

Also, are you able to work around this by temporarily downgrading pip (with python -m pip install --upgrade pip==19.3.1)?

**Comment by habeebmustafa** [comment] 2020-05-16 02:05
has this been resolved yet?

**Comment by omokoh** [comment] 2020-09-21 21:39
Hey

Are you still having this issue?

**Comment by habeebmustafa** [comment] 2020-09-21 23:13
Nope - i just gave up and found that for
Many users it was not required to be installed - 

My azure credentials had some problem and then it worked out without installing artifacts-keyring

Sent from my iPhone

On Sep 21, 2020, at 11:39 PM, Michael Omokoh <notifications@github.com> wrote:

﻿
Hey

Are you still having this issue?

**Comment by aaroncrespo** [comment] 2020-11-13 16:50
@omokoh @salvmd 

> @eibrunorodrigues, sorry I missed your post. What platform and Python version are you using?
> 
> Also, are you able to work around this by temporarily downgrading pip?
> `python -m pip install --upgrade pip==19.3.1`

This does not work.

```shell
$ /venv/bin/python3 -m pip --version
pip 19.3.1 from /venv/lib/python3.8/site-packages/pip (python 3.8)

$ /venv/bin/python3 -m pip install keyring==21.4.0 artifacts-keyring==0.2.10
Collecting keyring==21.4.0
  Using cached https://files.pythonhosted.org/packages/e4/ed/7be20815f248b0d6aae406783c2bee392640924623c4e17b50ca90c7f74d/keyring-21.4.0-py3-none-any.whl
Collecting artifacts-keyring==0.2.10
  Using cached https://files.pythonhosted.org/packages/52/76/ff9a816d6a9aa856552dfe6d9a85c0c905d74803a7c94e709256ba414ca3/artifacts_keyring-0.2.10-py2.py3-none-any.whl
ERROR: Could not find a version that satisfies the requirement dotnetcore2; sys_platform != "win32" and python_version >= "3.0" (from artifacts-keyring==0.2.10) (from versions: none)
ERROR: No matching distribution found for dotnetcore2; sys_platform != "win32" and python_version >= "3.0" (from artifacts-keyring==0.2.10)
WARNING: You are using pip version 19.3.1; however, version 20.2.4 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
```

We are now unable to upgrade our build environments and get OS updates for dev machines.

**Closed** 2021-05-26 00:09 UTC
Labels: aa-triaged, redirect-to-dev-community
